Set lower pins for sphinxcontrib
See https://github.com/sphinx-doc/sphinx/pull/9448 for more context, but `sphinx-build` breaks with versions of these `sphinxcontrib` dependencies if they aren't at a high-enough version

The error in question is:
```
Extension error:
Could not import extension sphinx.builders.epub3 (exception: cannot import name 'RemovedInSphinx40Warning' from 'sphinx.deprecation' 
```